config/routes.rb
Ccsnetvis::Application.routes.draw do
  resources :subnet_ip_addressesses

  resources :site_subnets

  resources :subnets

  resources :site_contacts

  resources :contacts

  resources :sites

  get "info/index"

  resources :ip_addresses

  root to: 'site_subnets#index'

end

app/models/site_subnet.rb
class SiteSubnet < ActiveRecord::Base
  belongs_to :site
  belongs_to :subnet
end

app/controllers/site_subnets_controller.rb
class SiteSubnetsController < ApplicationController
  # GET /site_subnets
  # GET /site_subnets.json
  def index
    @site_subnets = SiteSubnet.all
    @primary_site_subnets = SiteSubnet.where(:site_id => 1).all(:include => :subnet, :order => 'subnets.preference')
    @secondary_site_subnets = SiteSubnet.where(:site_id => 2).all(:include => :subnet, :order => 'subnets.preference')
    @ho_site_subnets = SiteSubnet.where(:site_id => 3).all(:include => :subnet, :order => 'subnets.preference')
    @remote_site_subnets = SiteSubnet.where("site_id > ?", 4).all(:include => :site, :order => 'sites.name')
    

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @site_subnets }
    end
  end

  # GET /site_subnets/1
  # GET /site_subnets/1.json
  def show
    @site_subnet = SiteSubnet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @site_subnet }
    end
  end

  # GET /site_subnets/new
  # GET /site_subnets/new.json
  def new
    @site_subnet = SiteSubnet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @site_subnet }
    end
  end

  # GET /site_subnets/1/edit
  def edit
    @site_subnet = SiteSubnet.find(params[:id])
  end

  # POST /site_subnets
  # POST /site_subnets.json
  def create
    @site_subnet = SiteSubnet.new(params[:site_subnet])

    respond_to do |format|
      if @site_subnet.save
        format.html { redirect_to @site_subnet, notice: 'Site subnet was successfully created.' }
        format.json { render json: @site_subnet, status: :created, location: @site_subnet }
      else
        format.html { render action: "new" }
        format.json { render json: @site_subnet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /site_subnets/1
  # PUT /site_subnets/1.json
  def update
    @site_subnet = SiteSubnet.find(params[:id])

    respond_to do |format|
      if @site_subnet.update_attributes(params[:site_subnet])
        format.html { redirect_to @site_subnet, notice: 'Site subnet was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @site_subnet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /site_subnets/1
  # DELETE /site_subnets/1.json
  def destroy
    @site_subnet = SiteSubnet.find(params[:id])
    @site_subnet.destroy

    respond_to do |format|
      format.html { redirect_to site_subnets_url }
      format.json { head :ok }
    end
  end
end

app/helpers/site_subnets_helper.rb
module SiteSubnetsHelper
end

app/views/site_subnets/_form.html.erb
<%= form_for(@site_subnet) do |f| %>
  <% if @site_subnet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site_subnet.errors.count, "error") %> prohibited this site_subnet from being saved:</h2>

      <ul>
      <% @site_subnet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<table>

  <table class="forum_view">
	<tr>
  <div class="field">
	<th>Site</th>
    <td><%= collection_select(:site_subnet, :site_id, Site.all(:order => 'name'), :id, :name) %></td>
  </div>
</tr>
<tr>
  <div class="field">
	<th>Subnet</th>
    <td><%= collection_select(:site_subnet, :subnet_id, Subnet.all(:order => 'network'), :id, :network) %></td>
  </div>
</tr>
<tr>
  <div class="actions">
    <td><%= f.submit %></td>
  </div>
</tr>
<% end %>
</table>

app/views/site_subnets/edit.html.erb
<div id="Wrapper" style="position: relative;">
	<div id="swap_to"></div>
	<div id="swap_from">
		<div id="screen_body" class="container">
			<div id="blank_slate" class="clearfix"></div>
			<table class="layout">
				<tr>
					<td class="left">
						<div class="Left">
							<div class="col">
								<div class="page_header">  <div class="page_header_links">
									<%= link_to 'Back', site_subnets_path %> | 
									<%= link_to 'Delete this connection', @site_subnet, confirm: 'Are you sure?', :class =>"admin", method: :delete %>
								  </div>
								  <h1>Edit this Site to Subnet Link</h1>
								</div>
							<div class="innercol">

<%= render 'form' %>
<br>
</div>
</div>
					<div class="bottom">
						&nbsp;
					</div>
					<div class="footer"></div>
				</div>
			</td>
			<td class="right">
				<div class="Right">
					<div class="col">


						  <h1>Create New :</h1>
						  <div class="indent people_on_project">
						  <%= link_to Subnet, new_subnet_path%></br>
						<%= link_to Site, new_site_path %></br>
						<%= link_to Contact, new_contact_path %></br>
						  </div>
						  <h1>Link:</h1>
						  <div class="indent people_on_project">
						  <%= link_to "Site to Subnet", new_site_subnet_path%></br>
						<%= link_to "Contact to Site", new_site_contact_path %></br>

						  </div>

    <div class="project_notifications">
      <h1>Report Bug or Get Help</h1>
      <div class="indent">
          <div class="digest_subscription">

            <span class="sprite email_icon" style="background: url(<%= asset_path 'basecamp_sprites.png' %>) no-repeat -190px -30px; width: 21px; padding-top: 21px; " title=""></span>
              <p><a href="mailto:jamyers@correctcaresolutions.com">Email Jason</a></p>
          </div>
      </div>
    </div>



                 </div>
               </div>
             </td>
           </tr>
        </table>
    </div>
  </div>
</div>
</body>
</html>

app/views/site_subnets/index.html.erb
<div id="Wrapper" style="position: relative;">
			<div id="swap_to"></div>
			<div id="swap_from">
				<div id="screen_body" class="container">
					<div id="blank_slate" class="clearfix"></div>
					<table class="layout">
						<tr>
							<td class="left">
								<div class="Left">
									<div class="col">
										<div class="page_header">
											<h1>
												Sites and Subnets Overview
											</h1>
										</div>
										<div class="innercol">
											<table>
												<tr>
													<td valign="top">
														<table>
															<tr>
																<th>
																	<% @site1 = SiteSubnet.find(8) %><%= @site1.site.name%>
																</th>
															</tr><% @primary_site_subnets.each do |main_subnet| %>
															<tr>
																<td>
																	<%= link_to main_subnet.subnet.network,subnet_path(main_subnet.subnet) %>
																</td>
															</tr><% end %>
														</table>
													</td>
													<td valign="top">
														<table>
															<tr>
																<th>
																	<% @site2 = SiteSubnet.find(4) %><%= @site2.site.name%>
																</th>
															</tr><% @secondary_site_subnets.each do |secondary_subnet| %>
															<tr>
																<td>
																	<%= link_to secondary_subnet.subnet.network,subnet_path(secondary_subnet.subnet) %>
																</td>
															</tr><% end %>
														</table>
													</td>
													<td valign="top">
														<table>
															<tr>
																<th>
																	<% @ho_site = SiteSubnet.find(10) %><%= @ho_site.site.name%>
																</th>
															</tr><% @ho_site_subnets.each do |ho_subnet| %>
															<tr>
																<td>
																	<%= link_to ho_subnet.subnet.network,subnet_path(ho_subnet.subnet) %>
																</td>
															</tr><% end %>
														</table>
													</td>
												</tr>
											</table>
											<hr>
											<table>
												<tr>
													<th>
														Remote Site
													</th>
													<th>
														Subnet
													</th>
												</tr><% @remote_site_subnets.each do |remote_site_subnet| %>
												<tr>
													<td>
														<%= remote_site_subnet.site.name %>
													</td>
													<td>
														<%= link_to remote_site_subnet.subnet.network, subnet_path(remote_site_subnet.subnet) %>
													</td>
												</tr><% end %>
											</table><br>
										</div>
									</div>
														<div class="bottom">
															&nbsp;
														</div>
														<div class="footer"></div>
													</div>
												</td>
												<td class="right">
													<div class="Right">
														<div class="col">


															  <h1>Create New :</h1>
															  <div class="indent people_on_project">
															  <%= link_to Subnet, new_subnet_path%></br>
															<%= link_to Site, new_site_path %></br>
															<%= link_to Contact, new_contact_path %></br>
															  </div>
															  <h1>Link:</h1>
															  <div class="indent people_on_project">
															  <%= link_to "Site to Subnet", new_site_subnet_path%></br>
															<%= link_to "Contact to Site", new_site_contact_path %></br>

															  </div>

									    <div class="project_notifications">
									      <h1>Report Bug or Get Help</h1>
									      <div class="indent">
									          <div class="digest_subscription">

									            <span class="sprite email_icon" style="background: url(<%= asset_path 'basecamp_sprites.png' %>) no-repeat -190px -30px; width: 21px; padding-top: 21px; " title=""></span>
									              <p><a href="mailto:jamyers@correctcaresolutions.com">Email Jason</a></p>
									          </div>
									      </div>
									    </div>



									                 </div>
									               </div>
									             </td>
									           </tr>
									        </table>
									    </div>
									  </div>
									</div>
									</body>
									</html>

app/views/site_subnets/new.html.erb
<div id="Wrapper" style="position: relative;">
	<div id="swap_to"></div>
	<div id="swap_from">
		<div id="screen_body" class="container">
			<div id="blank_slate" class="clearfix"></div>
			<table class="layout">
				<tr>
					<td class="left">
						<div class="Left">
							<div class="col">
								<div class="page_header">  <div class="page_header_links">
									<%= link_to 'Back', site_subnets_path %>
								  </div>
								  <h1>New Site to Subnet Link</h1>
								</div>
							<div class="innercol">

<%= render 'form' %>

<br>
</div>
</div>
					<div class="bottom">
						&nbsp;
					</div>
					<div class="footer"></div>
				</div>
			</td>
			<td class="right">
				<div class="Right">
					<div class="col">


						  <h1>Create New :</h1>
						  <div class="indent people_on_project">
						  <%= link_to Subnet, new_subnet_path%></br>
						<%= link_to Site, new_site_path %></br>
						<%= link_to Contact, new_contact_path %></br>
						  </div>
						  <h1>Link:</h1>
						  <div class="indent people_on_project">
						  <%= link_to "Site to Subnet", new_site_subnet_path%></br>
						<%= link_to "Contact to Site", new_site_contact_path %></br>

						  </div>

    <div class="project_notifications">
      <h1>Report Bug or Get Help</h1>
      <div class="indent">
          <div class="digest_subscription">

            <span class="sprite email_icon" style="background: url(<%= asset_path 'basecamp_sprites.png' %>) no-repeat -190px -30px; width: 21px; padding-top: 21px; " title=""></span>
              <p><a href="mailto:jamyers@correctcaresolutions.com">Email Jason</a></p>
          </div>
      </div>
    </div>



                 </div>
               </div>
             </td>
           </tr>
        </table>
    </div>
  </div>
</div>
</body>
</html>

app/views/site_subnets/show.html.erb
<div id="Wrapper" style="position: relative;">
	<div id="swap_to"></div>
	<div id="swap_from">
		<div id="screen_body" class="container">
			<div id="blank_slate" class="clearfix"></div>
			<table class="layout">
				<tr>
					<td class="left">
						<div class="Left">
							<div class="col">
								<div class="page_header">
									<div class="page_header_links">
										<%= link_to 'Back', site_subnets_path %> | 
										<%= link_to 'Edit', edit_site_subnet_path(@site_subnet) %> | 
										<%= link_to 'New', new_site_subnet_path %> | 
									    <%= link_to 'Delete this connection', @site_subnet, confirm: 'Are you sure?', :class =>"admin", method: :delete %>
									  </div>
									<h1>
										Site Listing
									</h1>
									</div>
									<div class="innercol">

<table>

  <table class="forum_view">
<tr>
  <th>Site:</th>
  <td><%= @site_subnet.site.name %></td>
</tr>
<tr>
  <th>Subnet:</th>
  <td><%= @site_subnet.subnet.network %></td>
</tr>

</table>

					<div class="bottom">
						&nbsp;
					</div>
					<div class="footer"></div>
				</div>
			</td>
			<td class="right">
				<div class="Right">
					<div class="col">


						  <h1>Create New :</h1>
						  <div class="indent people_on_project">
						  <%= link_to Subnet, new_subnet_path%></br>
						<%= link_to Site, new_site_path %></br>
						<%= link_to Contact, new_contact_path %></br>
						  </div>
						  <h1>Link:</h1>
						  <div class="indent people_on_project">
						  <%= link_to "Site to Subnet", new_site_subnet_path%></br>
						<%= link_to "Contact to Site", new_site_contact_path %></br>

						  </div>

    <div class="project_notifications">
      <h1>Report Bug or Get Help</h1>
      <div class="indent">
          <div class="digest_subscription">

            <span class="sprite email_icon" style="background: url(<%= asset_path 'basecamp_sprites.png' %>) no-repeat -190px -30px; width: 21px; padding-top: 21px; " title=""></span>
              <p><a href="mailto:jamyers@correctcaresolutions.com">Email Jason</a></p>
          </div>
      </div>
    </div>



                 </div>
               </div>
             </td>
           </tr>
        </table>
    </div>
  </div>
</div>
</body>
</html>