config/routes.rb
Ccsnetvis::Application.routes.draw do
  resources :subnet_ip_addressesses

  resources :site_subnets

  resources :subnets

  resources :site_contacts

  resources :contacts

  resources :sites

  get "info/index"

  resources :ip_addresses

  root to: 'site_subnets#index'

end

app/models/subnet.rb
class Subnet < ActiveRecord::Base
  has_many :site_subnets, dependent: :destroy
end

app/controllers/subnets_controller.rb
class SubnetsController < ApplicationController
  # GET /subnets
  # GET /subnets.json
  def index
    @subnets = Subnet.all(:order => "preference")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subnets }
    end
  end

  # GET /subnets/1
  # GET /subnets/1.json
  def show
    @subnet = Subnet.find(params[:id])
    @ip_addresses = IpAddress.all
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subnet }
    end
  end

  # GET /subnets/new
  # GET /subnets/new.json
  def new
    @subnet = Subnet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subnet }
    end
  end

  # GET /subnets/1/edit
  def edit
    @subnet = Subnet.find(params[:id])
  end

  # POST /subnets
  # POST /subnets.json
  def create
    @subnet = Subnet.new(params[:subnet])

    respond_to do |format|
      if @subnet.save
        format.html { redirect_to @subnet, notice: 'Subnet was successfully created.' }
        format.json { render json: @subnet, status: :created, location: @subnet }
      else
        format.html { render action: "new" }
        format.json { render json: @subnet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /subnets/1
  # PUT /subnets/1.json
  def update
    @subnet = Subnet.find(params[:id])

    respond_to do |format|
      if @subnet.update_attributes(params[:subnet])
        format.html { redirect_to @subnet, notice: 'Subnet was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @subnet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subnets/1
  # DELETE /subnets/1.json
  def destroy
    @subnet = Subnet.find(params[:id])
    @subnet.destroy

    respond_to do |format|
      format.html { redirect_to subnets_url }
      format.json { head :ok }
    end
  end
end

app/helpers/subnets_helper.rb
module SubnetsHelper
end

app/views/subnets/_form.html.erb
<%= form_for(@subnet) do |f| %>
  <% if @subnet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subnet.errors.count, "error") %> prohibited this subnet from being saved:</h2>

      <ul>
      <% @subnet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<table>

  <table class="forum_view">
	<tr>

  <div class="field">
    <th><%= f.label :network %></th>
    <td><%= f.text_field :network %></td>
  </div>
</tr>
<tr>
  <div class="field">
    <th><%= f.label :description %></th>
    <td><%= f.text_area :description, :rows=>5, :cols=>40 %></td>
  </div>
</tr>
<tr>	
  <div class="field">
    <th><%= f.label :netmask %></th>
    <td><%= f.text_field :netmask %></td>
  </div>
</tr>
<tr>
  <div class="field">
    <th><%= f.label :gateway %></th>
    <td><%= f.text_field :gateway %></td>
  </div>
</tr>
<tr>
  <div class="field">
    <th><%= f.label :preference %></th>
    <td><%= f.text_field :preference %><td>
  </div>
</tr>
<tr>
  <div class="actions">
    <td><%= f.submit %></td>
  </div>
</tr>
<% end %>
</table>

app/views/subnets/edit.html.erb
<div id="Wrapper" style="position: relative;">
	<div id="swap_to"></div>
	<div id="swap_from">
		<div id="screen_body" class="container">
			<div id="blank_slate" class="clearfix"></div>
			<table class="layout">
				<tr>
					<td class="left">
						<div class="Left">
							<div class="col">
								<div class="page_header">  <div class="page_header_links">
									<%= link_to 'Back', subnets_path %> | 
									<%= link_to 'Delete this site', @subnet, confirm: 'Are you sure?', :class =>"admin", method: :delete %>
								  </div>
								  <h1>Edit this Subnet</h1>
								</div>
							<div class="innercol">
<%= render 'form' %>
<br>
</div>
</div>
					<div class="bottom">
						&nbsp;
					</div>
					<div class="footer"></div>
				</div>
			</td>
			<td class="right">
				<div class="Right">
					<div class="col">


						  <h1>Create New :</h1>
						  <div class="indent people_on_project">
						  <%= link_to Subnet, new_subnet_path%></br>
						<%= link_to Site, new_site_path %></br>
						<%= link_to Contact, new_contact_path %></br>
						  </div>
						  <h1>Link:</h1>
						  <div class="indent people_on_project">
						  <%= link_to "Site to Subnet", new_site_subnet_path%></br>
						<%= link_to "Contact to Site", new_site_contact_path %></br>

						  </div>

    <div class="project_notifications">
      <h1>Report Bug or Get Help</h1>
      <div class="indent">
          <div class="digest_subscription">

            <span class="sprite email_icon" style="background: url(<%= asset_path 'basecamp_sprites.png' %>) no-repeat -190px -30px; width: 21px; padding-top: 21px; " title=""></span>
              <p><a href="mailto:jamyers@correctcaresolutions.com">Email Jason</a></p>
          </div>
      </div>
    </div>



                 </div>
               </div>
             </td>
           </tr>
        </table>
    </div>
  </div>
</div>
</body>
</html>

app/views/subnets/index.html.erb
<div id="Wrapper" style="position: relative;">
	<div id="swap_to"></div>
	<div id="swap_from">
		<div id="screen_body" class="container">
			<div id="blank_slate" class="clearfix"></div>
			<table class="layout">
				<tr>
					<td class="left">
						<div class="Left">
							<div class="col">
								<div class="page_header">
									<h1>
										Subnet Listing
									</h1>
									</div>
									<div class="innercol">

<table>  <table class="forum_view">
<% @subnets.each do |subnet| %>

    
<tr id="<%= subnet.id %>">
  <td class="message">
    <div style="margin-left: 40px;">
        <span class="title"><%= link_to subnet.network,edit_subnet_path(subnet) %></span>

      
      <br />
      <span class="meta">
        <%=subnet.description%>
      </span>
    </div>
  </td>
  <td class="last_comment">
  </td>
</tr>

<% end %>
</table>

<br />
<br>
</div>
</div>
					<div class="bottom">
						&nbsp;
					</div>
					<div class="footer"></div>
				</div>
			</td>
			<td class="right">
				<div class="Right">
					<div class="col">


						  <h1>Create New :</h1>
						  <div class="indent people_on_project">
						  <%= link_to Subnet, new_subnet_path%></br>
						<%= link_to Site, new_site_path %></br>
						<%= link_to Contact, new_contact_path %></br>
						  </div>
						  <h1>Link:</h1>
						  <div class="indent people_on_project">
						  <%= link_to "Site to Subnet", new_site_subnet_path%></br>
						<%= link_to "Contact to Site", new_site_contact_path %></br>

						  </div>
    <div class="project_notifications">
      <h1>Report Bug or Get Help</h1>
      <div class="indent">
          <div class="digest_subscription">

            <span class="sprite email_icon" style="background: url(<%= asset_path 'basecamp_sprites.png' %>) no-repeat -190px -30px; width: 21px; padding-top: 21px; " title=""></span>
              <p><a href="mailto:jamyers@correctcaresolutions.com">Email Jason</a></p>
          </div>
      </div>
    </div>



                 </div>
               </div>
             </td>
           </tr>
        </table>
    </div>
  </div>
</div>
</body>
</html>

app/views/subnets/new.html.erb
<div id="Wrapper" style="position: relative;">
	<div id="swap_to"></div>
	<div id="swap_from">
		<div id="screen_body" class="container">
			<div id="blank_slate" class="clearfix"></div>
			<table class="layout">
				<tr>
					<td class="left">
						<div class="Left">
							<div class="col">
								<div class="page_header">  <div class="page_header_links">
									<%= link_to 'Back', subnets_path %>
								  </div>
								  <h1>New Subnet</h1>
								</div>
							<div class="innercol">

<%= render 'form' %>
<br>
</div>
</div>
					<div class="bottom">
						&nbsp;
					</div>
					<div class="footer"></div>
				</div>
			</td>
			<td class="right">
				<div class="Right">
					<div class="col">


						  <h1>Create New :</h1>
						  <div class="indent people_on_project">
						  <%= link_to Subnet, new_subnet_path%></br>
						<%= link_to Site, new_site_path %></br>
						<%= link_to Contact, new_contact_path %></br>
						  </div>
						  <h1>Link:</h1>
						  <div class="indent people_on_project">
						  <%= link_to "Site to Subnet", new_site_subnet_path%></br>
						<%= link_to "Contact to Site", new_site_contact_path %></br>

						  </div>

    <div class="project_notifications">
      <h1>Report Bug or Get Help</h1>
      <div class="indent">
          <div class="digest_subscription">

            <span class="sprite email_icon" style="background: url(<%= asset_path 'basecamp_sprites.png' %>) no-repeat -190px -30px; width: 21px; padding-top: 21px; " title=""></span>
              <p><a href="mailto:jamyers@correctcaresolutions.com">Email Jason</a></p>
          </div>
      </div>
    </div>



                 </div>
               </div>
             </td>
           </tr>
        </table>
    </div>
  </div>
</div>
</body>
</html>

app/views/subnets/show.html.erb
<div id="Wrapper" style="position: relative;">
	<div id="swap_to"></div>
	<div id="swap_from">
		<div id="screen_body" class="container">
			<div id="blank_slate" class="clearfix"></div>
			<table class="layout">
				<tr>
					<td class="left">
						<div class="Left">
							<div class="col">
								<div class="page_header">  
										<div class="page_header_links">
										<%= link_to 'Add New IP', new_ip_address_path %>
									  </div>
									<h1>
										Subnet View
									</h1>
									</div>
									<div class="innercol">
<% @ip_parts=@subnet.network.split('.')%>
<% $ip_start="#{@ip_parts[0]}.#{@ip_parts[1]}.#{@ip_parts[2]}"%>

			<table class="forum_view">

				<% for i in (0..255) %>
					<% $ip_address = "#{$ip_start}.#{i}"%>
					<% @current_ip_address = IpAddress.where(:address => $ip_address).all%>
					<% @current_ip_address.each do |ip| %>
					<tr id="<%= ip.id %>">
					  <td class="message">
					    <div style="margin-left: 20px;">
					        <span class="title"><%= link_to ip.address, edit_ip_address_path(ip) %> - <%=ip.name%></span>


					      <br />
					      <span class="meta">
					        <%= ip.purpose %>
					      </span>
					    </div>
					  </td>

					</tr>

					<% end %>
				<% end %>
			</table>

					<div class="bottom">
						&nbsp;
					</div>
					<div class="footer"></div>
				</div>
			</td>
			<td class="right">
				<div class="Right">
					<div class="col">
						<h1>Subnet Info:</h1>
						  <div class="indent people_on_project">
						  	<table>
								<tr>
									<td><b>Network:</b></td><td><%= @subnet.network %></td>
								</tr>
								<tr>
									<td><b>Description:</b></td><td><%= @subnet.description %></td>
								</tr>
								<tr>
									<td><b>Netmask:</b></td><td><%= @subnet.netmask %></td>
								</tr>
								<tr>
									<td><b>Gateway:</b></td><td><%= @subnet.gateway %></td>
								</tr>
							</table>
						  </div>

						  <h1>Create New :</h1>
						  <div class="indent people_on_project">
						  <%= link_to Subnet, new_subnet_path%></br>
						<%= link_to Site, new_site_path %></br>
						<%= link_to Contact, new_contact_path %></br>
						  </div>
						  <h1>Link:</h1>
						  <div class="indent people_on_project">
						  <%= link_to "Site to Subnet", new_site_subnet_path%></br>
						<%= link_to "Contact to Site", new_site_contact_path %></br>

						  </div>

    <div class="project_notifications">
      <h1>Report Bug or Get Help</h1>
      <div class="indent">
          <div class="digest_subscription">

            <span class="sprite email_icon" style="background: url(<%= asset_path 'basecamp_sprites.png' %>) no-repeat -190px -30px; width: 21px; padding-top: 21px; " title=""></span>
              <p><a href="mailto:jamyers@correctcaresolutions.com">Email Jason</a></p>
          </div>
      </div>
    </div>



                 </div>
               </div>
             </td>
           </tr>
        </table>
    </div>
  </div>
</div>
</body>
</html>