config/routes.rb
Ccsnetvis::Application.routes.draw do
  resources :subnet_ip_addressesses

  resources :site_subnets

  resources :subnets

  resources :site_contacts

  resources :contacts

  resources :sites

  get "info/index"

  resources :ip_addresses

  root to: 'site_subnets#index'

end

app/controllers/ip_addresses_controller.rb
class IpAddressesController < ApplicationController
  # GET /ip_addresses
  # GET /ip_addresses.json
  def index
    @ip_addresses = IpAddress.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ip_addresses }
    end
  end

  # GET /ip_addresses/1
  # GET /ip_addresses/1.json
  def show
    @ip_address = IpAddress.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ip_address }
    end
  end

  # GET /ip_addresses/new
  # GET /ip_addresses/new.json
  def new
    @ip_address = IpAddress.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ip_address }
    end
  end

  # GET /ip_addresses/1/edit
  def edit
    @ip_address = IpAddress.find(params[:id])
  end

  # POST /ip_addresses
  # POST /ip_addresses.json
  def create
    @ip_address = IpAddress.new(params[:ip_address])

    respond_to do |format|
      if @ip_address.save
        format.html { redirect_to @ip_address, notice: 'Ip address was successfully created.' }
        format.json { render json: @ip_address, status: :created, location: @ip_address }
      else
        format.html { render action: "new" }
        format.json { render json: @ip_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ip_addresses/1
  # PUT /ip_addresses/1.json
  def update
    @ip_address = IpAddress.find(params[:id])

    respond_to do |format|
      if @ip_address.update_attributes(params[:ip_address])
        format.html { redirect_to @ip_address, notice: 'Ip address was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @ip_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ip_addresses/1
  # DELETE /ip_addresses/1.json
  def destroy
    @ip_address = IpAddress.find(params[:id])
    @ip_address.destroy

    respond_to do |format|
      format.html { redirect_to ip_addresses_url }
      format.json { head :ok }
    end
  end
end

app/helpers/ip_addresses_helper.rb
module IpAddressesHelper
end

app/views/ip_addresses/_form.html.erb
<%= form_for(@ip_address) do |f| %>
  <% if @ip_address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ip_address.errors.count, "error") %> prohibited this ip_address from being saved:</h2>

      <ul>
      <% @ip_address.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<table>

  <table class="forum_view">
	<tr>
  <div class="field">
    <th><%= f.label :address %></th>
    <td><%= f.text_field :address %></td>
  </div>
</tr><tr>
  <div class="field">
    <th><%= f.label :name %></th>
    <td><%= f.text_field :name %></td>
  </div>
</tr><tr>
  <div class="field">
    <th><%= f.label :purpose %></th>
    <td><%= f.text_field :purpose %></td>
  </div>
</tr><tr>
  <div class="field">
    <th><%= f.label :url %></th>
    <td><%= f.text_field :url %></td>
  </div>
</tr><tr>
  <div class="actions">
    <td><%= f.submit %></td>
  </div>
</tr>
<% end %>
</table>

app/views/ip_addresses/edit.html.erb
<div id="Wrapper" style="position: relative;">
	<div id="swap_to"></div>
	<div id="swap_from">
		<div id="screen_body" class="container">
			<div id="blank_slate" class="clearfix"></div>
			<table class="layout">
				<tr>
					<td class="left">
						<div class="Left">
							<div class="col">
								<div class="page_header">  <div class="page_header_links">
									<%= link_to 'Back', ip_addresses_path %> | 
									<%= link_to 'Delete this address', @ip_address, confirm: 'Are you sure?', :class =>"admin", method: :delete %>
								  </div>
								  <h1>Edit this IP Address</h1>
								</div>
							<div class="innercol">

<%= render 'form' %>
<br>
</div>
</div>
					<div class="bottom">
						&nbsp;
					</div>
					<div class="footer"></div>
				</div>
			</td>
			<td class="right">
				<div class="Right">
					<div class="col">


						  <h1>Create New :</h1>
						  <div class="indent people_on_project">
						  <%= link_to Subnet, new_subnet_path%></br>
						<%= link_to Site, new_site_path %></br>
						<%= link_to Contact, new_contact_path %></br>
						  </div>
						  <h1>Link:</h1>
						  <div class="indent people_on_project">
						  <%= link_to "Site to Subnet", new_site_subnet_path%></br>
						<%= link_to "Contact to Site", new_site_contact_path %></br>

						  </div>

    <div class="project_notifications">
      <h1>Report Bug or Get Help</h1>
      <div class="indent">
          <div class="digest_subscription">

            <span class="sprite email_icon" style="background: url(<%= asset_path 'basecamp_sprites.png' %>) no-repeat -190px -30px; width: 21px; padding-top: 21px; " title=""></span>
              <p><a href="mailto:jamyers@correctcaresolutions.com">Email Jason</a></p>
          </div>
      </div>
    </div>



                 </div>
               </div>
             </td>
           </tr>
        </table>
    </div>
  </div>
</div>
</body>
</html>

app/views/ip_addresses/index.html.erb
<div id="Wrapper" style="position: relative;">
	<div id="swap_to"></div>
	<div id="swap_from">
		<div id="screen_body" class="container">
			<div id="blank_slate" class="clearfix"></div>
			<table class="layout">
				<tr>
					<td class="left">
						<div class="Left">
							<div class="col">
								<div class="page_header">
									<h1>
										IP Address Listing
									</h1>
									</div>
									<div class="innercol">

<table>
  <table class="forum_view">
<% @ip_addresses.each do |ip_address| %>
<tr id="<%= ip_address.id %>">
  <td class="message">
    <div style="margin-left: 40px;">
        <span class="title"><%= link_to ip_address.address,ip_address_path(ip_address) %> - <%=ip_address.name%></span>

      
      <br />
      <span class="meta">
        <%= ip_address.purpose %>
      </span>
    </div>
  </td>
  <td class="last_comment">
  </td>
</tr>

<% end %>
</table>

<br />
<br>
</div>
</div>
					<div class="bottom">
						&nbsp;
					</div>
					<div class="footer"></div>
				</div>
			</td>
			<td class="right">
				<div class="Right">
					<div class="col">


						  <h1>Create New :</h1>
						  <div class="indent people_on_project">
						  <%= link_to Subnet, new_subnet_path%></br>
						<%= link_to Site, new_site_path %></br>
						<%= link_to Contact, new_contact_path %></br>
						  </div>
						  <h1>Link:</h1>
						  <div class="indent people_on_project">
						  <%= link_to "Site to Subnet", new_site_subnet_path%></br>
						<%= link_to "Contact to Site", new_site_contact_path %></br>

						  </div>
    <div class="project_notifications">
      <h1>Report Bug or Get Help</h1>
      <div class="indent">
          <div class="digest_subscription">

            <span class="sprite email_icon" style="background: url(<%= asset_path 'basecamp_sprites.png' %>) no-repeat -190px -30px; width: 21px; padding-top: 21px; " title=""></span>
              <p><a href="mailto:jamyers@correctcaresolutions.com">Email Jason</a></p>
          </div>
      </div>
    </div>



                 </div>
               </div>
             </td>
           </tr>
        </table>
    </div>
  </div>
</div>
</body>
</html>

app/views/ip_addresses/new.html.erb
<div id="Wrapper" style="position: relative;">
	<div id="swap_to"></div>
	<div id="swap_from">
		<div id="screen_body" class="container">
			<div id="blank_slate" class="clearfix"></div>
			<table class="layout">
				<tr>
					<td class="left">
						<div class="Left">
							<div class="col">
								<div class="page_header">  <div class="page_header_links">
									<%= link_to 'Back', ip_addresses_path %>
								  </div>
								  <h1>New IP Address</h1>
								</div>
							<div class="innercol">

<%= render 'form' %>

<br>
</div>
</div>
					<div class="bottom">
						&nbsp;
					</div>
					<div class="footer"></div>
				</div>
			</td>
			<td class="right">
				<div class="Right">
					<div class="col">


						  <h1>Create New :</h1>
						  <div class="indent people_on_project">
						  <%= link_to Subnet, new_subnet_path%></br>
						<%= link_to Site, new_site_path %></br>
						<%= link_to Contact, new_contact_path %></br>
						  </div>
						  <h1>Link:</h1>
						  <div class="indent people_on_project">
						  <%= link_to "Site to Subnet", new_site_subnet_path%></br>
						<%= link_to "Contact to Site", new_site_contact_path %></br>

						  </div>

    <div class="project_notifications">
      <h1>Report Bug or Get Help</h1>
      <div class="indent">
          <div class="digest_subscription">

            <span class="sprite email_icon" style="background: url(<%= asset_path 'basecamp_sprites.png' %>) no-repeat -190px -30px; width: 21px; padding-top: 21px; " title=""></span>
              <p><a href="mailto:jamyers@correctcaresolutions.com">Email Jason</a></p>
          </div>
      </div>
    </div>



                 </div>
               </div>
             </td>
           </tr>
        </table>
    </div>
  </div>
</div>
</body>
</html>

app/views/ip_addresses/show.html.erb
<div id="Wrapper" style="position: relative;">
	<div id="swap_to"></div>
	<div id="swap_from">
		<div id="screen_body" class="container">
			<div id="blank_slate" class="clearfix"></div>
			<table class="layout">
				<tr>
					<td class="left">
						<div class="Left">
							<div class="col">
								<div class="page_header">
									<div class="page_header_links">
										<%= link_to 'Back', ip_addresses_path %> | 
										<%= link_to 'Edit', edit_ip_address_path(@ip_address) %> | 
										<%= link_to 'New', new_ip_address_path %> | 
									    <%= link_to 'Delete this address', @ip_address, confirm: 'Are you sure?', :class =>"admin", method: :delete %>
									  </div>
									<h1>
										Site Listing
									</h1>
									</div>
									<div class="innercol">

<table>

  <table class="forum_view">
	<tr>
  <th>Address:</th>
  <td><%= @ip_address.address %></td>
</tr>

<tr>
  <th>Name:</th>
  <td><%= @ip_address.name %></td>
</tr>

<tr>
  <th>Purpose:</th>
  <td><%= @ip_address.purpose %><td>
</tr>

<tr>
  <th>Url:</th>
  <td><%= @ip_address.url %></td>
</tr>
</table>

					<div class="bottom">
						&nbsp;
					</div>
					<div class="footer"></div>
				</div>
			</td>
			<td class="right">
				<div class="Right">
					<div class="col">


						  <h1>Create New :</h1>
						  <div class="indent people_on_project">
						  <%= link_to Subnet, new_subnet_path%></br>
						<%= link_to Site, new_site_path %></br>
						<%= link_to Contact, new_contact_path %></br>
						  </div>
						  <h1>Link:</h1>
						  <div class="indent people_on_project">
						  <%= link_to "Site to Subnet", new_site_subnet_path%></br>
						<%= link_to "Contact to Site", new_site_contact_path %></br>

						  </div>

    <div class="project_notifications">
      <h1>Report Bug or Get Help</h1>
      <div class="indent">
          <div class="digest_subscription">

            <span class="sprite email_icon" style="background: url(<%= asset_path 'basecamp_sprites.png' %>) no-repeat -190px -30px; width: 21px; padding-top: 21px; " title=""></span>
              <p><a href="mailto:jamyers@correctcaresolutions.com">Email Jason</a></p>
          </div>
      </div>
    </div>



                 </div>
               </div>
             </td>
           </tr>
        </table>
    </div>
  </div>
</div>
</body>
</html>