config/routes.rb
Ccsnetvis::Application.routes.draw do
  resources :subnet_ip_addressesses

  resources :site_subnets

  resources :subnets

  resources :site_contacts

  resources :contacts

  resources :sites

  get "info/index"

  resources :ip_addresses

  root to: 'site_subnets#index'

end

app/models/site_contact.rb
class SiteContact < ActiveRecord::Base
  belongs_to :site
  belongs_to :contact
end

app/controllers/site_contacts_controller.rb
class SiteContactsController < ApplicationController
  # GET /site_contacts
  # GET /site_contacts.json
  def index
    @site_contacts = SiteContact.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @site_contacts }
    end
  end

  # GET /site_contacts/1
  # GET /site_contacts/1.json
  def show
    @site_contact = SiteContact.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @site_contact }
    end
  end

  # GET /site_contacts/new
  # GET /site_contacts/new.json
  def new
    @site_contact = SiteContact.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @site_contact }
    end
  end

  # GET /site_contacts/1/edit
  def edit
    @site_contact = SiteContact.find(params[:id])
  end

  # POST /site_contacts
  # POST /site_contacts.json
  def create
    @site_contact = SiteContact.new(params[:site_contact])

    respond_to do |format|
      if @site_contact.save
        format.html { redirect_to @site_contact, notice: 'Site contact was successfully created.' }
        format.json { render json: @site_contact, status: :created, location: @site_contact }
      else
        format.html { render action: "new" }
        format.json { render json: @site_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /site_contacts/1
  # PUT /site_contacts/1.json
  def update
    @site_contact = SiteContact.find(params[:id])

    respond_to do |format|
      if @site_contact.update_attributes(params[:site_contact])
        format.html { redirect_to @site_contact, notice: 'Site contact was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @site_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /site_contacts/1
  # DELETE /site_contacts/1.json
  def destroy
    @site_contact = SiteContact.find(params[:id])
    @site_contact.destroy

    respond_to do |format|
      format.html { redirect_to site_contacts_url }
      format.json { head :ok }
    end
  end
end

app/helpers/site_contacts_helper.rb
module SiteContactsHelper
end

app/views/site_contacts/_form.html.erb
<%= form_for(@site_contact) do |f| %>
  <% if @site_contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site_contact.errors.count, "error") %> prohibited this site_contact from being saved:</h2>

      <ul>
      <% @site_contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<table>

  <table class="forum_view">
	<tr>
    <div class="field">
	<th>Site</th>
	<td><%= collection_select(:site_contact, :site_id, Site.all, :id, :name) %></td>
  </div>
</tr>
<tr>
<div class="field">
	<th>Contact</th>
	<td><%= collection_select(:site_contact, :contact_id, Contact.all, :id, :name) %></td>
  </div>
</tr>
<tr>
  <div class="actions">
    <td><%= f.submit %></td>
  </div>
</tr>
<% end %>
</table>

app/views/site_contacts/edit.html.erb
<div id="Wrapper" style="position: relative;">
	<div id="swap_to"></div>
	<div id="swap_from">
		<div id="screen_body" class="container">
			<div id="blank_slate" class="clearfix"></div>
			<table class="layout">
				<tr>
					<td class="left">
						<div class="Left">
							<div class="col">
								<div class="page_header">  <div class="page_header_links">
									<%= link_to 'Back', site_contacts_path %> | 
									<%= link_to 'Delete this site', @site_contact, confirm: 'Are you sure?', :class =>"admin", method: :delete %>
								  </div>
								  <h1>Edit this Site to Contact Link</h1>
								</div>
							<div class="innercol">

<%= render 'form' %>
<br>
</div>
</div>
					<div class="bottom">
						&nbsp;
					</div>
					<div class="footer"></div>
				</div>
			</td>
			<td class="right">
				<div class="Right">
					<div class="col">


						  <h1>Create New :</h1>
						  <div class="indent people_on_project">
						  <%= link_to Subnet, new_subnet_path%></br>
						<%= link_to Site, new_site_path %></br>
						<%= link_to Contact, new_contact_path %></br>
						  </div>
						  <h1>Link:</h1>
						  <div class="indent people_on_project">
						  <%= link_to "Site to Subnet", new_site_subnet_path%></br>
						<%= link_to "Contact to Site", new_site_contact_path %></br>

						  </div>

    <div class="project_notifications">
      <h1>Report Bug or Get Help</h1>
      <div class="indent">
          <div class="digest_subscription">

            <span class="sprite email_icon" style="background: url(<%= asset_path 'basecamp_sprites.png' %>) no-repeat -190px -30px; width: 21px; padding-top: 21px; " title=""></span>
              <p><a href="mailto:jamyers@correctcaresolutions.com">Email Jason</a></p>
          </div>
      </div>
    </div>



                 </div>
               </div>
             </td>
           </tr>
        </table>
    </div>
  </div>
</div>
</body>
</html>

app/views/site_contacts/index.html.erb
<div id="Wrapper" style="position: relative;">
	<div id="swap_to"></div>
	<div id="swap_from">
		<div id="screen_body" class="container">
			<div id="blank_slate" class="clearfix"></div>
			<table class="layout">
				<tr>
					<td class="left">
						<div class="Left">
							<div class="col">
								<div class="page_header">
									<h1>
										Site to Contact Listing
									</h1>
									</div>
									<div class="innercol">

<table>  <table class="forum_view">
<% @site_contacts.each do |site_contact| %>
<tr id="<%= site_contact.id %>">
  <td class="message">
    <div style="margin-left: 40px;">
        <span class="title"><%= link_to site_contact.site.name,edit_site_contact_path(site_contact) %> - <%= site_contact.contact.name%></span>

      
      <br />
      <span class="meta">
      </span>
    </div>
  </td>
  <td class="last_comment">
  </td>
</tr>

<% end %>
</table>

<br />
<br>
</div>
</div>
					<div class="bottom">
						&nbsp;
					</div>
					<div class="footer"></div>
				</div>
			</td>
			<td class="right">
				<div class="Right">
					<div class="col">


						  <h1>Create New :</h1>
						  <div class="indent people_on_project">
						  <%= link_to Subnet, new_subnet_path%></br>
						<%= link_to Site, new_site_path %></br>
						<%= link_to Contact, new_contact_path %></br>
						  </div>
						  <h1>Link:</h1>
						  <div class="indent people_on_project">
						  <%= link_to "Site to Subnet", new_site_subnet_path%></br>
						<%= link_to "Contact to Site", new_site_contact_path %></br>

						  </div>
    <div class="project_notifications">
      <h1>Report Bug or Get Help</h1>
      <div class="indent">
          <div class="digest_subscription">

            <span class="sprite email_icon" style="background: url(<%= asset_path 'basecamp_sprites.png' %>) no-repeat -190px -30px; width: 21px; padding-top: 21px; " title=""></span>
              <p><a href="mailto:jamyers@correctcaresolutions.com">Email Jason</a></p>
          </div>
      </div>
    </div>



                 </div>
               </div>
             </td>
           </tr>
        </table>
    </div>
  </div>
</div>
</body>
</html>

app/views/site_contacts/new.html.erb
<div id="Wrapper" style="position: relative;">
	<div id="swap_to"></div>
	<div id="swap_from">
		<div id="screen_body" class="container">
			<div id="blank_slate" class="clearfix"></div>
			<table class="layout">
				<tr>
					<td class="left">
						<div class="Left">
							<div class="col">
								<div class="page_header">  <div class="page_header_links">
									<%= link_to 'Back', site_contacts_path %>
								  </div>
								  <h1>New Site to contact connection</h1>
								</div>
							<div class="innercol">
<%= render 'form' %>
<br>
</div>
</div>
					<div class="bottom">
						&nbsp;
					</div>
					<div class="footer"></div>
				</div>
			</td>
			<td class="right">
				<div class="Right">
					<div class="col">


						  <h1>Create New :</h1>
						  <div class="indent people_on_project">
						  <%= link_to Subnet, new_subnet_path%></br>
						<%= link_to Site, new_site_path %></br>
						<%= link_to Contact, new_contact_path %></br>
						  </div>
						  <h1>Link:</h1>
						  <div class="indent people_on_project">
						  <%= link_to "Site to Subnet", new_site_subnet_path%></br>
						<%= link_to "Contact to Site", new_site_contact_path %></br>

						  </div>

    <div class="project_notifications">
      <h1>Report Bug or Get Help</h1>
      <div class="indent">
          <div class="digest_subscription">

            <span class="sprite email_icon" style="background: url(<%= asset_path 'basecamp_sprites.png' %>) no-repeat -190px -30px; width: 21px; padding-top: 21px; " title=""></span>
              <p><a href="mailto:jamyers@correctcaresolutions.com">Email Jason</a></p>
          </div>
      </div>
    </div>



                 </div>
               </div>
             </td>
           </tr>
        </table>
    </div>
  </div>
</div>
</body>
</html>

app/views/site_contacts/show.html.erb
<div id="Wrapper" style="position: relative;">
	<div id="swap_to"></div>
	<div id="swap_from">
		<div id="screen_body" class="container">
			<div id="blank_slate" class="clearfix"></div>
			<table class="layout">
				<tr>
					<td class="left">
						<div class="Left">
							<div class="col">
								<div class="page_header">  
									<div class="page_header_links">
										<%= link_to 'Back', site_subnets_path %> | 
										<%= link_to 'Edit', edit_site_subnet_path(@site_subnet) %> | 
										<%= link_to 'New', new_site_subnet_path %> | 
									    <%= link_to 'Delete this address', @site_subnet, confirm: 'Are you sure?', :class =>"admin", method: :delete %>
									  </div>
									<h1>
										Site to subnet View
									</h1>
									</div>
									<div class="innercol">
										<table class="forum_view">
<tr>
  <th>Site:</th>
  <td><%= @site_contact.site.name %></td>
</tr>

<tr>
  <th>Contact:</th>
  <td><%= @site_contact.contact.name %><td>
</tr>

</table>

					<div class="bottom">
						&nbsp;
					</div>
					<div class="footer"></div>
				</div>
			</td>
			<td class="right">
				<div class="Right">
					<div class="col">


						  <h1>Create New :</h1>
						  <div class="indent people_on_project">
						  <%= link_to Subnet, new_subnet_path%></br>
						<%= link_to Site, new_site_path %></br>
						<%= link_to Contact, new_contact_path %></br>
						  </div>
						  <h1>Link:</h1>
						  <div class="indent people_on_project">
						  <%= link_to "Site to Subnet", new_site_subnet_path%></br>
						<%= link_to "Contact to Site", new_site_contact_path %></br>

						  </div>

    <div class="project_notifications">
      <h1>Report Bug or Get Help</h1>
      <div class="indent">
          <div class="digest_subscription">

            <span class="sprite email_icon" style="background: url(<%= asset_path 'basecamp_sprites.png' %>) no-repeat -190px -30px; width: 21px; padding-top: 21px; " title=""></span>
              <p><a href="mailto:jamyers@correctcaresolutions.com">Email Jason</a></p>
          </div>
      </div>
    </div>



                 </div>
               </div>
             </td>
           </tr>
        </table>
    </div>
  </div>
</div>
</body>
</html>